### PR TITLE
Profile settings

### PR DESCRIPTION
**Pull request by ZB103**

### CODE REVIEW

**Review by brycebailey287 — APPROVED** [review]
Looks good to me

**Comment by Will-Coker513** [comment]
Looks good!

**Review by Will-Coker513 — APPROVED** [review]
Looks good! I figured this out finally lol

**Comment by Con-Co-Industries** [comment]
Looks good, nice job

**Comment by Con-Co-Industries** [comment]
Sorry, wrong button. Did what Will did lol

**Review by Con-Co-Industries — APPROVED** [review]
Ok finally got it

**Pull request merged**
